In [38]:
import numpy as np

In [40]:
a = np.array([[9,  5,  6,  3,  6,  8,  0,  7,  9,  7,  2,  7],
              [1,  4,  9,  2,  2,  1,  0,  6,  2,  2,  4,  0]])

In [41]:
np.hsplit(a,3)   # 平均分成三份

[array([[9, 5, 6, 3],
        [1, 4, 9, 2]]),
 array([[6, 8, 0, 7],
        [2, 1, 0, 6]]),
 array([[9, 7, 2, 7],
        [2, 2, 4, 0]])]

In [42]:
np.hsplit(a,(3,4))   # 以第三列和第四列为界，分割数组

[array([[9, 5, 6],
        [1, 4, 9]]),
 array([[3],
        [2]]),
 array([[6, 8, 0, 7, 9, 7, 2, 7],
        [2, 1, 0, 6, 2, 2, 4, 0]])]

In [50]:
print(np.__version__)
np.show_config()

1.19.2
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/Application/Anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['D:/Application/Anaconda\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/Application/Anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['D:/Application/Anaconda\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/Application/Anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['D:/Application/Anaconda\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/Application/Anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['D:/Application/Anaconda\\Library\\include']
